# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["SpadayDagre"]


class SpadayDagre(Component):
    """Directed graph rendered as themed SVG, laid out by dagre from a serializable node/edge config."""

    tag = "spaday-dagre"
    schema = ComponentSchema(
        tag="spaday-dagre",
        class_name="SpadayDagre",
        summary="Directed graph rendered as themed SVG, laid out by dagre from a serializable node/edge config.",
        props=(
            PropertySchema(
                name="graph",
                kind="json",
                choices=(),
                default=None,
                description="The graph: {nodes: [{id, label, width, height, class}], edges: [{source, target, label, class}]}.",
            ),
            PropertySchema(
                name="layout",
                kind="json",
                choices=(),
                default=None,
                description="dagre layout options: rankdir (TB/BT/LR/RL), align, nodesep, edgesep, ranksep, marginx, marginy, ranker.",
            ),
        ),
        events=("dagre-node-click", "dagre-edge-click"),
        slots=(),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        graph: Any = None,
        layout: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "graph": graph,
                "layout": layout,
            },
            **props,
        )
